# Site settings
title: Gareth codes
email: me@gareth.codes
description: > # this means to ignore newlines until "baseurl:"
  Current home: Vancouver, Canada.
  Just finished a three year contract with Greenpeace International.
  Open to new adventures. Check résumé/cv for details 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gareth.codes" # the base hostname & protocol for your site
twitter_username: gyaresu
github_username: gyaresu 
timezone: Vancouver
permalink: /:title/
excerpt_separator: <!--more-->
exclude: ['README.md']

# http://jekyllrb.com/docs/configuration/
markdown: kramdown
kramdown:
    input: GFM
    auto_ids:       true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   lsquo,rsquo,ldquo,rdquo
    enable_coderay: false
    coderay:
        coderay_wrap:              div
        coderay_line_numbers:      inline
        coderay_line_number_start: 1
        coderay_tab_width:         4
        coderay_bold_every:        10
        coderay_css:               style
